app:
  name: My App
  description: Welcome to ${app.name}

my:
  greeting: Hello World from server
  list:
    values: One,Two,Three,four server

db:
  connection: "{connectionString: 'http://__',userName: 'foo',password: 'pass'}"
  host: 127.0.0.1
  port: 1200
spring:
  profiles:
    active: test
